scheduler_name: scx_flashyspark
workload_type: latency_sensitive

# Optimize for low-latency workloads
optimize_metric: pp_tokens_per_sec
reward_scaling: 2.0

# Scheduler parameters to optimize
scheduler_params:
  slice_us:
    type: integer
    default: 2048
    min_value: 128
    max_value: 8192
    description: Time slice in microseconds - shorter for latency
    command_arg: --slice-us
  
  slice_us_lag:
    type: integer
    default: 2048
    min_value: 512
    max_value: 8192
    description: Sleep budget in microseconds
    command_arg: --slice-us-lag
  
  cpu_busy_thresh:
    type: integer
    default: 50
    min_value: 10
    max_value: 90
    description: CPU utilization threshold for migration
    command_arg: --cpu-busy-thresh

# Training configuration
algorithm: ppo
episodes: 100
baseline_runs: 5
learning_rate: 1e-3
update_frequency: 5
save_frequency: 20

# Benchmark configuration
benchmark_cmd: "taskset -c 0-15 hackbench -g 10 -l 100"
timeout: 60
